<?php


namespace app\base\controller;


class AdminBaseController extends UserBaseController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (empty($this->logon_user['is_admin']))
            $this->error('仅管理员可访问');
    }
}