<?php


namespace app\base\controller;


class UserBaseController extends HomeBaseController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (empty($this->logon_user))
            $this->error('需要登录后才可使用', 'user/login/index');
    }
}